apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "cityflow" }}
  labels:
    name: {{ .Values.global.namespace | default "cityflow" }}
    {{- include "cityflow.labels" . | nindent 4 }}
